In [1]:
import tensorflow as tf

In [3]:
print(f"wersja tf: {tf.__version__}")

wersja tf: 2.10.1


In [5]:
mnist = tf.keras.datasets.mnist

(x_train,y_train),(x_test,y_test)=mnist.load_data()
x_train,x_test = x_train/255.0, x_test/255.0

In [6]:
x_train.shape

(60000, 28, 28)

In [7]:
x_test.shape

(10000, 28, 28)

In [8]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10) 

])

In [9]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.00379324, 0.94944566, 0.5320328 , -0.5967586 , -0.47845984,
 0.55582345, -0.21173221, -0.68312633, 0.0190423 , 0.08548231]],
 dtype=float32)

In [10]:
tf.nn.softmax(predictions).numpy()

array([[0.08573809, 0.222413 , 0.14651431, 0.04738623, 0.05333701,
 0.15004179, 0.06964132, 0.04346535, 0.08771849, 0.09374447]],
 dtype=float32)

In [11]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [12]:
loss_fn(y_train[:1],predictions).numpy()

1.8968415

In [13]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [14]:
model.fit(x_train,y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2909 - accuracy: 0.9152
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1405 - accuracy: 0.9574
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1060 - accuracy: 0.9679
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0879 - accuracy: 0.9732
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0755 - accuracy: 0.9768


In [15]:
model.evaluate(x_test,y_test,verbose=2)

313/313 - 1s - loss: 0.0789 - accuracy: 0.9760 - 554ms/epoch - 2ms/step


[0.07890626788139343, 0.9760000109672546]

In [16]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [17]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[7.21588655e-09, 8.52468762e-09, 1.78007588e-06, 7.91284139e-04,
        1.62445786e-11, 1.54535678e-06, 6.93571719e-13, 9.99187648e-01,
        1.56032706e-06, 1.61690805e-05],
       [5.46850254e-09, 8.09921185e-04, 9.99033928e-01, 9.02147367e-05,
        9.47756210e-14, 6.34845928e-05, 7.37484129e-07, 4.88639851e-10,
        1.82858173e-06, 6.06490752e-15],
       [1.44888259e-06, 9.98750925e-01, 7.22319601e-05, 1.10966175e-05,
        2.33328356e-05, 2.90855187e-05, 5.75572667e-05, 6.44471264e-04,
        4.09731758e-04, 1.70933433e-07],
       [9.99978781e-01, 2.47702747e-10, 8.58981457e-06, 5.47519448e-07,
        3.93694393e-08, 9.20402329e-07, 2.51002916e-06, 3.70983707e-06,
        8.45910506e-07, 4.15006434e-06],
       [6.38897700e-06, 3.81705734e-09, 2.69938459e-06, 4.07702565e-08,
        9.98800159e-01, 8.83728092e-07, 3.98519614e-06, 2.58257060e-05,
        7.35144056e-07, 1.15917716e-03]], dtype=float32)>