In [1]:
import numpy as np

In [2]:
# stwórz tensor oparty na 32 elementowym wektorze 
# Creating a 32-element vector
vector = np.arange(32)
# Reshaping the vector into a 5-D tensor
tensor = vector.reshape((2, 2, 2, 2, 2))

In [3]:
tensor

array([[[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]]],


        [[[ 8,  9],
          [10, 11]],

         [[12, 13],
          [14, 15]]]],



       [[[[16, 17],
          [18, 19]],

         [[20, 21],
          [22, 23]]],


        [[[24, 25],
          [26, 27]],

         [[28, 29],
          [30, 31]]]]])

To jest pierwszy **notebook** oparty na mechanizmie <span style="color:red;font-size:20pt;">Jupyter Notebook</span>

In [4]:
wektor= np.array([5,2,6,3,6,3,6,3])
wektor

array([5, 2, 6, 3, 6, 3, 6, 3])

In [5]:
w = np.array([[1,2,3,4],[9,10,11,12],[34,27,89,54]])

In [6]:
w

array([[ 1, 2, 3, 4],
 [ 9, 10, 11, 12],
 [34, 27, 89, 54]])

In [7]:
w[w<5]

array([1, 2, 3, 4])

In [8]:
pc = (w>5)
w[pc]

array([ 9, 10, 11, 12, 34, 27, 89, 54])

In [9]:
lw = (w%2==0)
w[lw]

array([ 2, 4, 10, 12, 34, 54])

In [10]:
cv = w[(w>2)&(w<=21)]
cv

array([ 3, 4, 9, 10, 11, 12])

In [11]:
dane = np.array([1,3,8])
one = np.ones(3,dtype=int)
tw = np.array([2,2,3])

In [12]:
print(dane+one)

[2 4 9]


In [13]:
print(dane-one)

[0 2 7]


In [14]:
print(dane*tw)

[ 2  6 24]


In [15]:
m1 = np.array([[4,8,11],[67,101,3],[1,1,77]])
m2 = np.array([[488,9,3],[23,89,3],[2,4,11]])

wynik = (m1+m2)*m1
wynik

array([[ 1968, 136, 154],
 [ 6030, 19190, 18],
 [ 3, 5, 6776]])

In [16]:
print(f'wartość minimum: {wynik.min()}')
print(f'wartość maksimum: {wynik.max()}')
print(f'wartość średnia: {wynik.mean()}')
print(f'wartość średnie odchyl std: {wynik.std()}')

wartość minimum: 3
wartość maksimum: 19190
wartość średnia: 3808.8888888888887
wartość średnie odchyl std: 5998.870809381906
